# Generated by Django 6.0.5 on 2026-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='receipt_location',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='Ячейка хранения чека'),
        ),
    ]
